### ISSUE TITLE
Rotation lock not working in PWA on chrome on android 

### ISSUE THREAD

**Issue by tomhense** [izderadicka/audioserve-web#17]
Hi

I have the issue that audioserve ignores the android rotation lock when I use as a PWA with chrome on android 14, so when I have my phone locked in portrait it still rotates the page if I turn my phone.

This issue doesn't seem to be fault of audioserve but rather because chrome implements the orientation [spec](https://www.w3.org/TR/screen-orientation/#screen-orientation-types) of the webmanifest wrong.

I would maybe suggest just removing the orientation property in the webmanifest. Or is there any specific reason that it is in there? It doesn't seem to be a required property.

[A stackoverflow report on the same issue](https://stackoverflow.com/questions/73956593/pwa-ignores-os-orientation-lock-on-android)

Thanks in advance :)

**Comment by izderadicka** [comment]
Fixed, thanks for providing details - I think chrome  might be right as I have `orientation: any` in manifest, so it may override device settings. Not sure why it was there, but without it it works as expected. 
PWA application has to be uninstalled  and installed again for new manifest to take effect.
