### ISSUE TITLE
Book Progress Layout Issue

### ISSUE THREAD

**Issue by OrangeDrangon** [izderadicka/audioserve-web#3]
Book progress do not have enough space to properly display the numbers even though the window is plenty large.

![image](https://user-images.githubusercontent.com/25403517/161456648-c4901648-8dca-432b-bcd0-8c6b8858916c.png)

**Comment by izderadicka** [comment]
Thanks,  all UI is still in progress,  with focus on functionality now.  I'm not good UI designer, so more iteration will be needed to settle the layout, any help is welcomed, so thanks for reporting.

Just couple of additional questions -   which browser? what platform,  what is actual resolution of window  - window.innerWidth and window.outerWidth.

**Comment by OrangeDrangon** [comment]
Sorry about the crappy bug report. Here are some more details

Chromium
Linux

Specific window size does not seem to matter. It renders fine on my phone but using device simulator on my computer browser it never is properly laid out. I suspect it may have something to do with my system font.

**Comment by izderadicka** [comment]
Should be fixed now in latest master
