### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by OrangeDrangon** [izderadicka/audioserve-web#4]
The current Dark theme looks fine when the background color is changed to black. This is preferable for OLED screens common on phones. Instead of a dark mode toggle, a theme drop down could be implemented with Light, Dark, and Black.

**Comment by izderadicka** [comment]
I just used defaults from picocss.    Would not be big issues change/add theme, but is not a priority now.  But open for PRs.

Apart of changing background color, change in menu background (which is back in dark theme, so should be changed a bit to something bit different)  And to choose theme selection logic in menu

**Comment by izderadicka** [comment]
As I'm using dark theme on mobile, I made it's background black. Looks fine on Samsung.  As current css framework offers just light and dark these out of box, I'll stick to it for now. Another themes could be added, but this will be more work then I'm will to invest now, rather I'll focus on other features.
