### ISSUE TITLE
Playback Control Cursor

### ISSUE THREAD

**Issue by OrangeDrangon** [izderadicka/audioserve-web#6]
The cursor for the playback controls is not marked as pointer.

**Comment by izderadicka** [comment]
True,  playback controls are still WIP, will fix in some next iteration

**Comment by OrangeDrangon** [comment]
Just as a note I do not mean to be annoying. Just reporting things I notice. Thanks for the awesome project.

**Comment by OrangeDrangon** [comment]
Fixed in latest batch of commits.
