### ISSUE TITLE
Force Rescan for Files

### ISSUE THREAD

**Issue by OrangeDrangon** [izderadicka/audioserve-web#7]
Not sure if this is a server or frontend issue.

I managed to get the server in a state where files were copied into a directory but not displayed in the UI. No amount of restarts of the server made them show up. I ended up moving them in and out of the directory to make them be detected. 

I have no idea how to reproduce this but it would be nice to be able to force the server to rescan a directory.

**Comment by izderadicka** [comment]
Server is scanning  directory via inotify. It's bit complex code, I hoped I made it right, obviously these is still is an issue. I will need to know exact steps how to replicate and will be gratefull if you"ll identify exact scenario.

If your collection is bigger there might be problem with os limit on inotify - pls see readme on details. 

Also there is  simple fix to this - force full rescan of folders -  send signal USR1 to process or run with argument  `---force-cache-update`. Again more info in readme.

More info is needed about volume :

- local or network?
- file system
- if running in docker how is it mounted

**Comment by OrangeDrangon** [comment]
`ls -R | wc -l` gave about 1500. Not all of those are audio files but I guess my collection is pretty big. Server is hosted on a VPS running in `docker-compose` using a directory mount. I think the file system is XFS. The VPS manages the partitions when I created it.

Sorry I missed those details in the README. Thanks.

**Comment by izderadicka** [comment]
1500 files/dirs should work with default value of inotify watches (unless
consumed by other services).  I also use XFS or ext4,  but have not tested
with docker.

As containers share kernel limit of inotify watches is per host system.

What would be interesting to know if in your case audioserve is not
following changes in collection directories at all, or it was just some
specific scenario, when it did not catch the changes.

**Comment by izderadicka** [comment]
This "theoretically" should be covered, so replicable test case that fails is welcomed.

Move within collection directory is complex case cause I try to keep already scanned subdirectories. There can be some corner case that will cause problems.

**Comment by OrangeDrangon** [comment]
I'll play with reproduction later.
